/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableCellRenderer;
import org.jfree.chart.ChartFrame;

/**
 *
 * @author Aditia Farhan
 */
public class highscores extends javax.swing.JFrame {
    KumpulanHighScore hs= new KumpulanHighScore();    
    ChartFrame a ;
    
    /**
     * Creates new form highscores
     */
    public highscores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smp = new javax.swing.JTabbedPane();
        PanelSD = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Nama2 = new javax.swing.JLabel();
        btnMenu2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TabelSD = new javax.swing.JTable();
        PanelSMP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nama1 = new javax.swing.JLabel();
        btnMenu1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        TabelSMP = new javax.swing.JTable();
        PanelSMA = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        TabelSMA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(380, 100));
        setMinimumSize(new java.awt.Dimension(500, 450));
        setResizable(false);

        smp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        smp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                smpFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Distant Galaxy", 1, 24)); // NOI18N
        jLabel3.setText("High Score");

        Nama2.setFont(new java.awt.Font("Distant Galaxy", 1, 18)); // NOI18N
        Nama2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nama2.setText("SD");

        btnMenu2.setBackground(new java.awt.Color(224, 224, 224));
        btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu2.setBorder(null);
        btnMenu2.setBorderPainted(false);
        btnMenu2.setContentAreaFilled(false);
        btnMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenu2MouseReleased(evt);
            }
        });
        btnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2ActionPerformed(evt);
            }
        });

        setLocation(225,200);
        TabelSD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        NO", "                Nama", "           Skor", "    Sisa  Waktu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelSD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TabelSD.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        TabelSD.getColumn("        NO").setCellRenderer( centerRenderer );
        TabelSD.getColumn("                Nama").setCellRenderer( centerRenderer );
        TabelSD.getColumn("           Skor").setCellRenderer( centerRenderer );
        TabelSD.getColumn("    Sisa  Waktu").setCellRenderer( centerRenderer );
        jScrollPane5.setViewportView(TabelSD);
        if (TabelSD.getColumnModel().getColumnCount() > 0) {
            TabelSD.getColumnModel().getColumn(0).setResizable(false);
            TabelSD.getColumnModel().getColumn(0).setPreferredWidth(8);
            TabelSD.getColumnModel().getColumn(1).setResizable(false);
            TabelSD.getColumnModel().getColumn(2).setResizable(false);
            TabelSD.getColumnModel().getColumn(2).setPreferredWidth(45);
            TabelSD.getColumnModel().getColumn(3).setResizable(false);
            TabelSD.getColumnModel().getColumn(3).setPreferredWidth(45);
        }

        javax.swing.GroupLayout PanelSDLayout = new javax.swing.GroupLayout(PanelSD);
        PanelSD.setLayout(PanelSDLayout);
        PanelSDLayout.setHorizontalGroup(
            PanelSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSDLayout.createSequentialGroup()
                .addGroup(PanelSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSDLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel3))
                    .addGroup(PanelSDLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(PanelSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nama2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenu2))))
                .addContainerGap(235, Short.MAX_VALUE))
            .addGroup(PanelSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSDLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(86, Short.MAX_VALUE)))
        );
        PanelSDLayout.setVerticalGroup(
            PanelSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nama2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(btnMenu2)
                .addGap(19, 19, 19))
            .addGroup(PanelSDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSDLayout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        smp.addTab("HIGHSCORE SD", PanelSD);

        jLabel2.setFont(new java.awt.Font("Distant Galaxy", 1, 24)); // NOI18N
        jLabel2.setText("High Score");

        Nama1.setFont(new java.awt.Font("Distant Galaxy", 1, 18)); // NOI18N
        Nama1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nama1.setText("SMP");

        btnMenu1.setBackground(new java.awt.Color(224, 224, 224));
        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu1.setBorder(null);
        btnMenu1.setBorderPainted(false);
        btnMenu1.setContentAreaFilled(false);
        btnMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenu1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenu1MouseReleased(evt);
            }
        });
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        setLocation(225,200);
        TabelSMP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        NO", "                Nama", "           Skor", "    Sisa  Waktu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        TabelSMP.getColumn("        NO").setCellRenderer( centerRenderer );
        TabelSMP.getColumn("                Nama").setCellRenderer( centerRenderer );
        TabelSMP.getColumn("           Skor").setCellRenderer( centerRenderer );
        TabelSMP.getColumn("    Sisa  Waktu").setCellRenderer( centerRenderer );
        jScrollPane8.setViewportView(TabelSMP);
        if (TabelSMP.getColumnModel().getColumnCount() > 0) {
            TabelSMP.getColumnModel().getColumn(0).setResizable(false);
            TabelSMP.getColumnModel().getColumn(0).setPreferredWidth(8);
            TabelSMP.getColumnModel().getColumn(1).setResizable(false);
            TabelSMP.getColumnModel().getColumn(2).setResizable(false);
            TabelSMP.getColumnModel().getColumn(2).setPreferredWidth(45);
            TabelSMP.getColumnModel().getColumn(3).setResizable(false);
            TabelSMP.getColumnModel().getColumn(3).setPreferredWidth(45);
        }

        javax.swing.GroupLayout PanelSMPLayout = new javax.swing.GroupLayout(PanelSMP);
        PanelSMP.setLayout(PanelSMPLayout);
        PanelSMPLayout.setHorizontalGroup(
            PanelSMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSMPLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel2)
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSMPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelSMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMenu1)
                    .addComponent(Nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(240, 240, 240))
            .addGroup(PanelSMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSMPLayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(86, Short.MAX_VALUE)))
        );
        PanelSMPLayout.setVerticalGroup(
            PanelSMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSMPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Nama1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                .addComponent(btnMenu1)
                .addContainerGap())
            .addGroup(PanelSMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSMPLayout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        smp.addTab("HIGHSCORE SMP", PanelSMP);

        jLabel1.setFont(new java.awt.Font("Distant Galaxy", 1, 24)); // NOI18N
        jLabel1.setText("High Score");

        Nama.setFont(new java.awt.Font("Distant Galaxy", 1, 18)); // NOI18N
        Nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nama.setText("SMA");

        btnMenu.setBackground(new java.awt.Color(224, 224, 224));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuMouseReleased(evt);
            }
        });
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        setLocation(225,200);
        TabelSMA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        NO", "                Nama", "           Skor", "    Sisa  Waktu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        TabelSMA.getColumn("        NO").setCellRenderer( centerRenderer );
        TabelSMA.getColumn("                Nama").setCellRenderer( centerRenderer );
        TabelSMA.getColumn("           Skor").setCellRenderer( centerRenderer );
        TabelSMA.getColumn("    Sisa  Waktu").setCellRenderer( centerRenderer );
        jScrollPane9.setViewportView(TabelSMA);
        if (TabelSMA.getColumnModel().getColumnCount() > 0) {
            TabelSMA.getColumnModel().getColumn(0).setResizable(false);
            TabelSMA.getColumnModel().getColumn(0).setPreferredWidth(8);
            TabelSMA.getColumnModel().getColumn(1).setResizable(false);
            TabelSMA.getColumnModel().getColumn(2).setResizable(false);
            TabelSMA.getColumnModel().getColumn(2).setPreferredWidth(45);
            TabelSMA.getColumnModel().getColumn(3).setResizable(false);
            TabelSMA.getColumnModel().getColumn(3).setPreferredWidth(45);
        }

        javax.swing.GroupLayout PanelSMALayout = new javax.swing.GroupLayout(PanelSMA);
        PanelSMA.setLayout(PanelSMALayout);
        PanelSMALayout.setHorizontalGroup(
            PanelSMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSMALayout.createSequentialGroup()
                .addGap(20, 233, Short.MAX_VALUE)
                .addGroup(PanelSMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu))
                .addGap(0, 256, Short.MAX_VALUE))
            .addGroup(PanelSMALayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelSMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSMALayout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(86, Short.MAX_VALUE)))
        );
        PanelSMALayout.setVerticalGroup(
            PanelSMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSMALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(btnMenu)
                .addContainerGap())
            .addGroup(PanelSMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSMALayout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        smp.addTab("HIGHSCORE SMA", PanelSMA);
        a=hs.TampilHighScore(TabelSD,"SD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(smp)
        );

        setBounds(175, 162, 627, 489);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/menu-hover.png"));
        btnMenu.setIcon(II);
    }//GEN-LAST:event_btnMenuMousePressed

    private void btnMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/menu.png"));
        btnMenu.setIcon(II);
    }//GEN-LAST:event_btnMenuMouseReleased

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        close();        
    }//GEN-LAST:event_btnMenuActionPerformed

    private void close(){
        a.dispose();
        dispose();
        MainMenu mm = new MainMenu();
        mm.setVisible(true);
    }
    
    private void btnMenu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/menu-hover.png"));
        btnMenu.setIcon(II);
    }//GEN-LAST:event_btnMenu1MousePressed

    private void btnMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/menu.png"));
        btnMenu.setIcon(II);
    }//GEN-LAST:event_btnMenu1MouseReleased

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        close();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu2MousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/menu-hover.png"));
        btnMenu.setIcon(II);
    }//GEN-LAST:event_btnMenu2MousePressed

    private void btnMenu2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu2MouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/menu.png"));
        btnMenu.setIcon(II);
    }//GEN-LAST:event_btnMenu2MouseReleased

    private void btnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2ActionPerformed
        close();
    }//GEN-LAST:event_btnMenu2ActionPerformed

    private void smpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_smpFocusGained
         if (smp.getSelectedIndex()==0){           
            a.dispose();
            a=hs.TampilHighScore(TabelSD,"SD");
        }else if(smp.getSelectedIndex()==1){            
            a.dispose();
            a=hs.TampilHighScore(TabelSMP,"SMP");
        }else{
            a.dispose();
            a=hs.TampilHighScore(TabelSMA,"SMA");
        }
    }//GEN-LAST:event_smpFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(highscores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(highscores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(highscores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(highscores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new highscores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nama1;
    private javax.swing.JLabel Nama2;
    private javax.swing.JPanel PanelSD;
    private javax.swing.JPanel PanelSMA;
    private javax.swing.JPanel PanelSMP;
    public javax.swing.JTable TabelSD;
    public javax.swing.JTable TabelSMA;
    public javax.swing.JTable TabelSMP;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnMenu2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane smp;
    // End of variables declaration//GEN-END:variables
}
