/*as
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aditia Farhan
 */
public class KalahNyawa extends javax.swing.JDialog {

    /**
     * Creates new form KalahNyawa
     */
    
    private String nama;
    private int skor;
    private String kunci;
    private String level;
    public KalahNyawa(java.awt.Frame parent, boolean modal,String nama,int skor,String kunci,String level) {
        super(parent, modal);
        this.nama=nama;
        this.skor=skor;
        this.kunci=kunci;
        this.level=level;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jkey = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jskor = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(450, 130));
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/heart.png.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 120, 140));

        jLabel1.setFont(new java.awt.Font("Bernard MT Condensed", 1, 48)); // NOI18N
        jLabel1.setText("GAME OVER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 300, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/test.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel5.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("YOU'RE RUNNING OUT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 270, -1));

        jLabel6.setFont(new java.awt.Font("Bernard MT Condensed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("OF LIFE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 100, -1));

        jkey.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        jkey.setText("Lorem Ipsum Dolor");
        getContentPane().add(jkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 190, 30));

        jname.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        jname.setText("Lorem Ipsum Dolor");
        getContentPane().add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jskor.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        jskor.setText("XXX");
        getContentPane().add(jskor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 60, -1));

        jLabel11.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        jLabel11.setText("THE ANSWER IS  :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 160, 30));

        jLabel12.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        jLabel12.setText("NAME                    :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bernard MT Condensed", 1, 18)); // NOI18N
        jLabel13.setText("SCORE                  :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 180, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/continue2.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 130, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mainmenu2.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/milimeterblock.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 520));
        Sound.SoundLose();
        jkey.setText(kunci);
        jname.setText(nama);
        jskor.setText(String.valueOf(skor));

        setSize(new java.awt.Dimension(505, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Sound.SoundButton();
        dispose();
        MainMenu mn = new MainMenu();
        mn.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Sound.SoundButton();
        dispose();
        Ui_soal_sd soal1;
        Ui_soal_smp soal2;
        Ui_soal_sma soal3;
        if(level.equalsIgnoreCase("SD")){                        
            try {
                soal1 = new Ui_soal_sd();
                soal1.setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(KalahWaktu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(level.equalsIgnoreCase("SMP")){
            try {
                soal2 = new Ui_soal_smp();
                soal2.setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(KalahWaktu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                soal3 = new Ui_soal_sma();
                soal3.setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(KalahWaktu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        Sound.SoundLose();
//        jkey.setText(kunci);
//        jname.setText(nama);
//        jskor.setText(String.valueOf(skor));
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalahNyawa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalahNyawa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalahNyawa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalahNyawa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KalahNyawa dialog = new KalahNyawa(new javax.swing.JFrame(), true,"rtyu",6,"iuytr","ASDF");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jkey;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel jskor;
    // End of variables declaration//GEN-END:variables
}
