/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
/**
 *
 * @author Lorem Ipsum Dolor
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    public MainMenu() {
       initComponents();
       Image i = new ImageIcon(ClassLoader.getSystemResource("img/icon.png")).getImage();
       setIconImage(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnHTP = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        btnHigh = new javax.swing.JButton();
        btnCredits = new javax.swing.JButton();
        btnOption = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Player = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CheckMath");
        setBackground(new java.awt.Color(224, 224, 224));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(450, 200));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cloud.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-70, 80, 440, 270);

        btnHTP.setBackground(new java.awt.Color(224, 224, 224));
        btnHTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/htp.png"))); // NOI18N
        btnHTP.setBorderPainted(false);
        btnHTP.setContentAreaFilled(false);
        btnHTP.setFocusPainted(false);
        btnHTP.setFocusTraversalPolicyProvider(true);
        btnHTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHTPMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHTPMouseReleased(evt);
            }
        });
        btnHTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHTPActionPerformed(evt);
            }
        });
        getContentPane().add(btnHTP);
        btnHTP.setBounds(370, 110, 90, 46);

        btnPlay.setBackground(new java.awt.Color(224, 224, 224));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Play.png"))); // NOI18N
        btnPlay.setBorderPainted(false);
        btnPlay.setContentAreaFilled(false);
        btnPlay.setFocusPainted(false);
        btnPlay.setFocusTraversalPolicyProvider(true);
        btnPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPlayMouseReleased(evt);
            }
        });
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlay);
        btnPlay.setBounds(370, 70, 90, 50);

        btnHigh.setBackground(new java.awt.Color(224, 224, 224));
        btnHigh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/high score.png"))); // NOI18N
        btnHigh.setBorderPainted(false);
        btnHigh.setContentAreaFilled(false);
        btnHigh.setFocusPainted(false);
        btnHigh.setFocusTraversalPolicyProvider(true);
        btnHigh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHighMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHighMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHighMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHighMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHighMouseExited(evt);
            }
        });
        btnHigh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHighActionPerformed(evt);
            }
        });
        getContentPane().add(btnHigh);
        btnHigh.setBounds(370, 150, 90, 53);

        btnCredits.setBackground(new java.awt.Color(224, 224, 224));
        btnCredits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/credit.png"))); // NOI18N
        btnCredits.setBorderPainted(false);
        btnCredits.setContentAreaFilled(false);
        btnCredits.setFocusPainted(false);
        btnCredits.setFocusTraversalPolicyProvider(true);
        btnCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreditsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreditsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreditsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCreditsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCreditsMouseReleased(evt);
            }
        });
        btnCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditsActionPerformed(evt);
            }
        });
        getContentPane().add(btnCredits);
        btnCredits.setBounds(370, 230, 90, 53);

        btnOption.setBackground(new java.awt.Color(224, 224, 224));
        btnOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/option.png"))); // NOI18N
        btnOption.setBorderPainted(false);
        btnOption.setContentAreaFilled(false);
        btnOption.setFocusPainted(false);
        btnOption.setFocusTraversalPolicyProvider(true);
        btnOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOptionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOptionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOptionMouseReleased(evt);
            }
        });
        btnOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionActionPerformed(evt);
            }
        });
        getContentPane().add(btnOption);
        btnOption.setBounds(370, 190, 90, 53);

        btnExit.setBackground(new java.awt.Color(224, 224, 224));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setFocusPainted(false);
        btnExit.setFocusTraversalPolicyProvider(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(370, 270, 90, 53);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG DI CHECK MATH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 10, 400, 25);

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel3.setText(null);
        Player pemain = new Player();
        jLabel3.setText(pemain.get_nama());
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 40, 101, 20);

        Player.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        Player.setText("Player :");
        getContentPane().add(Player);
        Player.setBounds(170, 40, 60, 20);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/milimeterblock.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 670, 380);

        getAccessibleContext().setAccessibleName("CheckMate");

        setSize(new java.awt.Dimension(524, 397));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditsActionPerformed
        // TODO add your handling code here:
        Sound.SoundButton();
        dispose();
        Credits c = new Credits();
        c.setVisible(true);
    }//GEN-LAST:event_btnCreditsActionPerformed

    private void btnCreditsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditsMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/credit.png"));
        btnCredits.setIcon(II);
    }//GEN-LAST:event_btnCreditsMouseReleased

    private void btnCreditsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditsMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/credit-hover.png"));
        btnCredits.setIcon(II);
    }//GEN-LAST:event_btnCreditsMousePressed

    private void btnCreditsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditsMouseExited

    private void btnCreditsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditsMouseEntered

    private void btnCreditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditsMouseClicked

    private void btnOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionActionPerformed
        // TODO add your handling code here:
        Sound.SoundButton();
        dispose();
        Option o = new Option();
        o.setVisible(true);
    }//GEN-LAST:event_btnOptionActionPerformed

    private void btnOptionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/option.png"));
        btnOption.setIcon(II);
    }//GEN-LAST:event_btnOptionMouseReleased

    private void btnOptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/option-hover.png"));
        btnOption.setIcon(II);
    }//GEN-LAST:event_btnOptionMousePressed

    private void btnOptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOptionMouseExited

    private void btnOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOptionMouseEntered

    private void btnOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOptionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOptionMouseClicked

    private void btnHighActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHighActionPerformed
        // TODO add your handling code here:
        Sound.SoundButton();
        dispose();
        highscores hs = new highscores();
        KumpulanHighScore tr = new KumpulanHighScore();
        tr.print();
        hs.setVisible(true);
    }//GEN-LAST:event_btnHighActionPerformed

    private void btnHighMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHighMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/high score.png"));
        btnHigh.setIcon(II);
    }//GEN-LAST:event_btnHighMouseReleased

    private void btnHighMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHighMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/high score - hover.png"));
        btnHigh.setIcon(II);
    }//GEN-LAST:event_btnHighMousePressed

    private void btnHighMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHighMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHighMouseExited

    private void btnHighMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHighMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHighMouseEntered

    private void btnHighMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHighMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHighMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Sound.SoundButton();
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/exit.png"));
        btnExit.setIcon(II);
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/exit-hover.png"));
        btnExit.setIcon(II);
        
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnExitMouseClicked

    private void btnPlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/play-hover.png"));
        btnPlay.setIcon(II);
    }//GEN-LAST:event_btnPlayMousePressed

    private void btnHTPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHTPMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/htp-hover.png"));
        btnHTP.setIcon(II);
    }//GEN-LAST:event_btnHTPMousePressed

    private void btnHTPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHTPMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/htp.png"));
        btnHTP.setIcon(II);
    }//GEN-LAST:event_btnHTPMouseReleased

    private void btnPlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlayMouseReleased
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/img/Play.png"));
        btnPlay.setIcon(II);
    }//GEN-LAST:event_btnPlayMouseReleased

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        //MainMenu mm = new MainMenu();
        Sound.SoundButton(); 
        dispose();
        PilihLevel pl = new PilihLevel();
        pl.setVisible(true);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnHTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHTPActionPerformed
        // TODO add your handling code here:
        Sound.SoundButton();
        dispose();
        HowToPlay h = new HowToPlay();
        h.setVisible(true);
    }//GEN-LAST:event_btnHTPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() { 
                new MainMenu().setVisible(true); 
            }
    });         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Player;
    private javax.swing.JButton btnCredits;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHTP;
    private javax.swing.JButton btnHigh;
    private javax.swing.JButton btnOption;
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

}
